import React, { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "ar";

const translations = {
  en: {
    // Header
    nav_browse: "Browse",
    nav_auctions: "Live Auctions",
    nav_admin: "Admin",
    nav_list: "List Your Car",
    nav_favorites: "My Favorites",
    nav_admin_panel: "Admin Panel",
    nav_sign_out: "Sign Out",

    // Home Hero
    hero_badge: "live auction{s} running now",
    hero_h1_1: "Where premium",
    hero_h1_2: "used cars",
    hero_h1_3: "find their owner.",
    hero_p: "Browse our verified inventory, join live auctions in real time, and win the car you actually want — with full protection.",
    hero_btn_auction: "Enter Live Auction",
    hero_btn_browse: "Browse Cars",
    hero_stat_listed: "Cars Listed",
    hero_stat_live: "Live Now",
    hero_stat_verified: "Verified",
    hero_viewers: "Viewers",
    hero_bid_now: "Bid Now",

    // Search
    search_placeholder: "Try 'McLaren', 'Toyota', 'Cairo'…",
    search_btn: "Search",

    // Home sections
    live_now: "Live Now",
    bidding_in_progress: "Bidding in progress",
    view_all: "View all",
    all_cars: "All cars",
    curated: "Curated",
    featured_inventory: "Featured inventory",
    new_cars_section: "New Cars",
    used_cars_section: "Used Cars",
    new_cars_label: "Brand New",
    used_cars_label: "Pre-owned",

    // Features
    feat1_title: "Verified Listings",
    feat1_desc: "Every car is inspected and verified. Every listing comes with a full condition report.",
    feat2_title: "Real-Time Bidding",
    feat2_desc: "Sub-100ms updates. See every bid, every raise, the moment it happens.",
    feat3_title: "AI Price Insight",
    feat3_desc: "Know fair market value before you bid. Predictive pricing on every listing.",

    // CTA (kept for potential future use)
    cta_h: "Find your next",
    cta_h2: "premium car.",
    cta_p: "Browse {n}+ verified listings, join live auctions, and drive away with confidence.",
    cta_btn1: "Browse Cars",
    cta_btn2: "Contact Us",

    // Browse
    browse_title: "Browse Cars",
    browse_mobile_ph: "Brand, model, city…",
    browse_filters: "Filters",
    browse_active: "{n} active",
    browse_brand: "Brand",
    browse_all_brands: "All Brands",
    browse_city: "City",
    browse_all_cities: "All Cities",
    browse_max_price: "Max Price",
    browse_live_only: "Live auctions only",
    browse_reset: "Reset",
    browse_results: "{n} cars",
    browse_no_results: "No cars match your filters.",
    browse_reset_filters: "Reset Filters",
    browse_car_type: "Car Type",
    browse_type_all: "All",

    // Auctions
    auctions_title: "Live Auctions",
    auctions_p: "Pay the entry fee, place real-time bids, and win premium vehicles backed by buyer protection.",
    auctions_none_title: "No live auctions right now",
    auctions_none_p: "Check back soon or browse all listings.",
    auctions_browse: "Browse Cars",
    auctions_ends_in: "Ends in",
    auctions_bids: "bids",
    auctions_bid_now: "Bid Now",
    auctions_upcoming: "Upcoming",
    auctions_upcoming_title: "Upcoming Auctions",
    auctions_upcoming_p: "These listings will go live soon.",
    auctions_notify: "Notify Me",

    // Car detail
    car_live_badge: "LIVE AUCTION",
    car_verified: "Verified",
    car_watching: "watching now",
    car_specs: "Specifications",
    car_condition: "Condition Report",
    car_options_title: "Additional Options",
    car_current_bid: "Current Bid",
    car_ends_in: "Ends in",
    car_your_bid: "Your bid",
    car_place_bid: "Place Bid",
    car_placing: "Placing…",
    car_entry_fee: "Entry fee {n} · refunded if you don't win",
    car_bid_history: "Bid History",
    car_buy_now: "Buy Now",
    car_buy_now_price: "Buy Now Price",
    car_reserve_not_met: "Reserve not met",
    car_contact: "Contact Dealer",
    car_back: "Browse",
    car_share: "Share",
    car_related: "You may also like",
    car_overall: "Overall",
    car_accidents: "Accident History",
    car_no_accidents: "None reported",
    car_accident_yes: "Yes — disclosed",
    car_service: "Service History",

    // CarCard
    card_current_bid: "Current Bid",
    card_buy_now: "Buy Now",
    card_bids: "Bids",
    card_verified: "Verified",
    card_fav_add: "Added to favorites ♥",
    card_fav_remove: "Removed from favorites",

    // Footer
    footer_tagline: "The premium destination for used-car auctions. Verified inventory, live bidding, secure payments.",
    footer_marketplace: "Marketplace",
    footer_company: "Company",
    footer_support: "Support",
    footer_browse: "Browse",
    footer_auctions: "Live Auctions",
    footer_featured: "Featured",
    footer_list: "List Your Car",
    footer_about: "About",
    footer_careers: "Careers",
    footer_press: "Press",
    footer_contact: "Contact",
    footer_help: "Help Center",
    footer_protection: "Buyer Protection",
    footer_verification: "Verification",
    footer_terms: "Terms",
    footer_copy: "© 2026 APEXAuto. All rights reserved.",
    footer_crafted: "Crafted for collectors.",

    // List your car
    list_badge: "Verified listing program",
    list_title: "List your car. Sell it faster.",
    list_p: "Join Egypt's fastest-growing premium car auction platform and reach serious buyers instantly.",
    list_name: "Full Name *",
    list_email: "Email *",
    list_phone: "Phone",
    list_brand: "Car Brand *",
    list_model: "Model *",
    list_year: "Year",
    list_price: "Expected Price (EGP)",
    list_submit: "Submit Listing Request",
    list_success_title: "Request Received!",
    list_success_p: "Our team will contact you within 24 hours to complete your listing.",
    list_success_back: "Back to Home",

    // Favorites
    fav_title: "My Favorites",
    fav_empty: "No favorites yet",
    fav_empty_p: "Heart a car to save it here.",
    fav_browse: "Browse Cars",

    // Condition labels
    cond_engine: "Engine",
    cond_transmission: "Transmission",
    cond_suspension: "Suspension",
    cond_battery: "Battery",
    cond_tires: "Tires",
    cond_chassis: "Chassis",
    cond_interior: "Interior",
    cond_paint: "Paint",
    cond_prev_owners: "Prev. Owners",
    cond_license: "License Expiry",

    // Options labels
    opt_sunroof: "Sunroof",
    opt_rear_camera: "Rear Camera",
    opt_parking_sensors: "Parking Sensors",
    opt_infotainment: "Infotainment Screen",
    opt_navigation: "Navigation",
    opt_leather_seats: "Leather Seats",
    opt_heated_seats: "Heated Seats",
    opt_ventilated_seats: "Ventilated Seats",
    opt_cruise_control: "Cruise Control",
    opt_keyless_entry: "Keyless Entry",
    opt_push_start: "Push Start",
    opt_auto_ac: "Auto AC",
    opt_abs: "ABS Brakes",
    opt_esp: "ESP Stability",
    opt_airbags: "Airbags",
    opt_options_title: "Options",

    // Admin
    admin_super: "Super Admin",
    admin_ctrl: "Control",
    admin_ctrl2: "Center",
    admin_export_csv: "Export CSV",
    admin_add_car: "Add Car",
    admin_stat_sold_val: "Sold Cars Value",
    admin_stat_live: "Live Auctions",
    admin_stat_cars: "Total Cars",
    admin_stat_users: "Registered Users",
    admin_chart_title: "Auction Revenue",
    admin_chart_sub: "Last 12 weeks",
    admin_live_mon: "Live Monitoring",
    admin_no_live: "No live auctions right now.",
    admin_inventory: "Car Inventory",
    admin_submissions: "Listing Submissions",
    admin_submissions_sub: "Cars submitted via \"List Your Car\"",
    admin_hero_spot: "Hero Spotlight",
    admin_hero_sub: "The car shown in the homepage hero. Auto-selects the soonest-ending live auction, or pin any car manually.",
    admin_hero_pin: "Pin a specific car to the hero spotlight",
    admin_hero_auto: "— Auto (soonest live or best car) —",
    admin_hero_save: "Save",
    admin_hero_clear: "Clear (Auto)",
    admin_pinned: "Pinned",
    admin_auto_sel: "Auto-selected",
    admin_entry_req: "Auction Entry Requests",
    admin_entry_sub: "Users requesting to join live auctions via manual payment proof",
    admin_deposit_cfg: "Deposit Settings",
    admin_deposit_amt: "Deposit Amount (EGP)",
    admin_pay_info: "Payment Info (account/phone shown to user)",
    admin_save_settings: "Save Settings",
    admin_approve_entry: "Approve Entry",
    admin_approve: "Approve",
    admin_reject: "Reject",
    admin_reset_pending: "Reset to Pending",
    admin_view_proof: "View Payment Proof",
    admin_hide_proof: "Hide Proof",
    admin_reject_reason: "Rejection reason (optional)",
    admin_refund_ip: "Refund Instapay:",
    admin_deposit_lbl: "Deposit:",
    admin_car_lbl: "Car:",
    admin_no_entries: "No entry requests yet.",
    admin_sold_arch: "Sold Cars Archive",
    admin_sold_sub: "Completed auctions and buy-now sales",
    admin_reg_users: "Registered Users",
    admin_reg_users_sub: "Users registered via the login/register page",
    admin_messages: "Buyer Messages",
    admin_messages_sub: "Conversations from car detail pages",
    admin_no_msgs: "No messages yet.",
    admin_reply_ph: "Reply as dealer…",
    admin_reply: "Reply",
    admin_sending: "Sending…",
    admin_you_admin: "You (Admin)",
    admin_breakdown: "Inventory Breakdown",
    admin_by_brand: "Cars by brand",
    admin_total: "total",
    admin_pending: "pending",
    admin_conversations: "conversations",
    admin_no_subs: "No submissions yet.",
    admin_no_sold: "No sold cars yet.",
    admin_no_users: "No registered users yet.",
    admin_click_full: "Click image to view full size",
    admin_tab_overview: "Overview",
    admin_tab_cars: "Cars",
    admin_tab_requests: "Requests",
    admin_tab_people: "Users & Chat",

    nav_home: "Home",
    nav_calendar: "Calendar",
    nav_sell: "Sell",
    nav_saved: "Saved",
    badge_live: "LIVE",
    badge_sold: "SOLD",
    badge_best: "Best",
    badge_upcoming: "Upcoming Auction",
    badge_verified_buyer: "Verified Buyer",
    common_yes: "Yes",
    common_no: "No",
    common_close: "Close",
    common_saving: "Saving…",
    common_submitting: "Submitting…",
    common_user: "User",
    common_more: "more",
    common_none: "None",
    common_ended: "Ended",
    common_unknown: "Unknown",
    common_na: "—",

    header_search_ph: "Search brand, model, city...",
    header_search_see_all: 'See all results for "{q}"',
    header_search_none: 'No cars found for "{q}"',
    header_search_type: "Type to search cars...",
    header_notif_title: "Notifications",
    header_notif_view_all: "View all",
    header_notif_empty: "No notifications yet",

    footer_toast_about: "About page coming soon",
    footer_toast_careers: "Careers page coming soon",
    footer_toast_press: "Press kit coming soon",
    footer_toast_contact: "Contact us at: hello@apexauto.com",
    footer_toast_help: "Help center coming soon",
    footer_toast_protection: "All purchases include full buyer protection",
    footer_toast_verification: "All dealers are KYC-verified",
    footer_toast_terms: "Terms of service available on request",

    toast_img_upload_ok: "Image uploaded successfully",
    toast_img_upload_fail: "Image upload failed",
    toast_hero_updated: "Hero spotlight updated",
    toast_hero_auto: "Hero spotlight set to auto",
    toast_hero_fail: "Failed to update hero spotlight",
    toast_entry_approved: "Entry approved — user can now bid",
    toast_entry_status: "Entry {status}",
    toast_entry_fail: "Failed to update entry status",
    toast_deposit_saved: "Deposit settings saved",
    toast_settings_fail: "Failed to save settings",
    toast_request_status: "Request {status}",
    toast_request_fail: "Failed to update status",
    toast_reply_sent: "Reply sent",
    toast_reply_fail: "Failed to send reply",
    toast_csv_exported: "Inventory exported as CSV",
    toast_fill_required: "Fill required fields: Title, Brand, Model, Dealership, City",
    toast_car_updated: "{title} updated",
    toast_car_added: "{title} added to inventory",
    toast_save_fail: "Failed to save",
    toast_car_deleted: "{title} deleted",
    toast_delete_fail: "Failed to delete",
    toast_car_unlisted: "{title} unlisted",
    toast_update_fail: "Failed to update",
    toast_valid_end: "Please set a valid end date & time",
    toast_end_future: "End time must be in the future",
    toast_now_live: "{title} is now LIVE!",
    toast_go_live_fail: "Failed to go live",
    toast_featured: "{title} featured",
    toast_unfeatured: "{title} unfeatured",
    toast_auction_end_set: "Auction end time set to {duration} from now",
    toast_duration_minutes: "{n} minutes",
    toast_duration_hours: "{n} hours",
    toast_week_revenue: "Week {n}: EGP {amount}",
    toast_fill_fields: "Please fill in all required fields",
    toast_submit_fail: "Failed to submit request. Please try again.",
    toast_upload_proof: "Please upload your payment screenshot",
    toast_instapay_required: "Please enter your Instapay number for the refund",
    toast_entry_submitted: "Request submitted — the admin will review it shortly.",
    toast_bid_placed: "Bid placed: {amount} ✓",
    toast_bid_fail: "Failed to place bid",
    toast_sign_in_bid: "Please sign in to place a bid",
    toast_min_bid: "Minimum bid is {amount}",
    toast_entry_pending: "Your entry request is pending admin review.",
    toast_link_copied: "Link copied to clipboard!",
    toast_compare_removed: "Removed from comparison",
    toast_compare_added: "Added to comparison",
    toast_compare_max: "Maximum 3 cars can be compared at once",
    toast_proxy_min: "Max bid must be greater than current bid of {amount}",
    toast_proxy_set: "Proxy bid set to {amount}. We'll bid automatically up to this amount.",
    toast_proxy_fail: "Failed to set proxy bid",
    toast_price_alert_removed: "Price alert removed",
    toast_price_alert_set: "Price alert set for {amount}",
    toast_popup_blocked: "Please allow popups to print",
    toast_msg_fail: "Failed to send message",
    toast_reservation_ok: "Reservation confirmed! We'll contact you within 2 hours.",

    notif_entry_submitted_title: "Auction entry request sent",
    notif_entry_submitted_body: "Your deposit proof for {car} has been submitted. You'll be notified once the admin reviews it.",
    notif_entry_approved_title: "Auction entry approved",
    notif_entry_approved_body: "You've been approved to bid on {car}. Good luck!",
    notif_entry_rejected_title: "Auction entry not approved",
    notif_entry_rejected_body: "Your entry request for {car} was not approved. Upload a new proof to try again.",

    sell_hero_badge: "List Your Car",
    sell_hero_title: "Sell Through APEXAuto",
    sell_hero_p: "Submit your car details and our team will review your listing request. We'll contact you within 24 hours.",
    sell_why_price: "Best Price",
    sell_why_price_d: "Competitive auction pricing",
    sell_why_verified: "Verified",
    sell_why_verified_d: "Full inspection process",
    sell_why_fast: "Fast",
    sell_why_fast_d: "Listed within 48 hours",
    sell_success_title: "Request Submitted!",
    sell_success_p: "Our team will review your listing and contact you at {email} within 24 hours.",
    sell_browse: "Browse Cars",
    sell_another: "Submit Another",
    sell_info_title: "Your Information",
    sell_info_sub: "We'll use this to contact you about your listing",
    sell_car_title: "Car Details",
    sell_car_sub: "Tell us about the car you'd like to sell",
    sell_notes: "Additional Notes",
    sell_notes_ph: "Condition, mileage, modifications, service history, reason for selling…",
    sell_asking_price: "Your Asking Price (EGP)",
    sell_agree: "By submitting, you agree to our review process. Our team will reach out within 24 hours.",
    sell_email: "Email Address",

    entry_title: "Request Auction Entry",
    entry_deposit_required: "Deposit required to join this auction",
    entry_refund_note: "If you don't win, {pct} of your deposit (EGP {amount}) will be refunded to your Instapay account.",
    entry_refund_pct: "80% of your deposit",
    entry_fee_note: "The remaining 20% (EGP {amount}) covers administrative and processing fees and is non-refundable.",
    entry_transfer_to: "Transfer to",
    entry_pay_not_configured: "Payment info not configured. Contact admin.",
    entry_instapay: "Your Instapay number",
    entry_instapay_hint: "We'll send your refund to this number if you don't win.",
    entry_instapay_ph: "e.g. 01012345678",
    entry_upload_proof: "Upload payment proof",
    entry_upload_hint: "Screenshot of your Instapay / bank transfer confirmation.",
    entry_upload_click: "Click to upload screenshot",
    entry_submit: "Submit Request",
    entry_approved: "You're approved to bid on this auction",
    entry_pending: "Your entry request is pending review",
    entry_rejected: "Entry rejected. Upload a new proof to try again.",
    entry_request_btn: "Request Entry",

    car_not_found: "Car not found",
    car_back_browse: "Back to browse",
    car_has_accidents: "Has Accidents",
    car_no_accidents_label: "No Accidents",
    car_overall_condition: "Overall Condition",
    car_hp_unit: "{n} hp",
    car_km_unit: "{n} km",

    compare_title: "Compare Cars",
    compare_empty_p: "Add cars from browse to compare side by side.",
    compare_count: "Comparing {n} car(s)",
    compare_clear: "Clear All",
    compare_none_title: "No cars to compare",
    compare_none_p: "Go to Browse and click the compare icon on any car card to add it here.",
    compare_view_listing: "View listing",
    compare_spec_price: "Price",
    compare_spec_year: "Year",
    compare_spec_mileage: "Mileage",
    compare_spec_engine: "Engine",
    compare_spec_hp: "Horsepower",
    compare_spec_fuel: "Fuel",
    compare_spec_transmission: "Transmission",
    compare_spec_color: "Color",
    compare_spec_seats: "Seats",
    compare_spec_condition: "Condition",
    compare_spec_accidents: "Accident History",
    compare_spec_city: "City",
    compare_spec_dealer: "Dealership",
    compare_spec_options: "Options",

    calendar_badge: "Schedule",
    calendar_title: "Auction Calendar",
    calendar_p: "Track live and upcoming auction end times.",
    calendar_live_count: "{n} Live Now",
    calendar_no_end: "No End Date",
    calendar_upcoming: "Upcoming ({n})",
    calendar_none: "No upcoming auctions scheduled.",
    calendar_view_live: "View Live Auctions",

    sold_badge: "Auction Archive",
    sold_title: "Sold Listings",
    sold_p: "Browse completed auctions, final hammer prices, and historical sale data.",
    sold_stat_total: "Total Sold",
    sold_stat_value: "Total Value",
    sold_stat_avg: "Avg. Sale Price",
    sold_stat_record: "Record Sale",
    sold_empty_title: "No sold listings yet",
    sold_empty_p: "Completed auctions will appear here once the hammer falls.",
    sold_final_price: "Final Price",
    sold_starting: "Starting:",
    sold_bids: "{n} bids",

    account_tab_bids: "My Bids",
    account_tab_notif: "Notifications",
    account_tab_recent: "Recently Viewed",
    account_tab_searches: "Saved Searches",
    account_tab_profile: "Profile",
    account_stat_bids: "Total Bids",
    account_stat_cars: "Cars Bid On",
    account_stat_active: "Active",
    account_stat_won: "Won",
    account_stat_favorites: "Favorites",
    account_clear_notif: "Clear All",
    account_mark_read: "Mark all read",
    account_no_bids: "No bids yet",
    account_no_bids_p: "Join a live auction and place your first bid.",
    account_view_auctions: "View Live Auctions",
    account_no_notif: "No notifications",
    account_no_recent: "No recently viewed cars",
    account_no_searches: "No saved searches",
    account_save_search: "Save Search",
    account_search_ph: "Search query…",
    account_profile_title: "Profile Settings",
    account_name: "Full Name",
    account_email: "Email",
    account_phone: "Phone",
    account_save: "Save Profile",
    account_sign_out: "Sign Out",
    account_bid_on: "Bid on",
    account_status_won: "Won",
    account_status_outbid: "Outbid",
    account_status_active: "Active",
    account_status_ended: "Ended",

    auth_tagline: "Premium used car auctions",

    admin_form_edit: "Edit Car",
    admin_form_add: "Add New Car",
    admin_form_editing: "Editing: {title}",
    admin_form_subtitle: "Complete all sections for best results",
    admin_form_tab_basic: "Basic Info",
    admin_form_tab_mechanical: "Mechanical",
    admin_form_tab_condition: "Condition",
    admin_form_tab_options: "Options",
    admin_form_tab_media: "Media",
    admin_form_tab_auction: "Auction",
    admin_sec_identity: "Identity",
    admin_sec_location: "Location & Dealer",
    admin_sec_pricing: "Pricing",
    admin_sec_description: "Description",
    admin_sec_flags: "Flags",
    admin_sec_engine: "Engine & Power",
    admin_sec_drivetrain: "Drivetrain & Specs",
    admin_sec_primary_img: "Primary Image",
    admin_sec_gallery: "Image Gallery",
    admin_sec_videos: "Videos",
    admin_sec_auction_pricing: "Auction Pricing",
    admin_sec_auction_end: "Auction End Time",
    admin_sec_auction_status: "Auction Status",
    admin_lbl_title: "Title *",
    admin_lbl_brand: "Brand *",
    admin_lbl_model: "Model *",
    admin_lbl_year: "Year",
    admin_lbl_trim: "Trim",
    admin_lbl_vin: "VIN",
    admin_lbl_plate: "Plate Status",
    admin_lbl_color: "Color",
    admin_lbl_dealership: "Dealership *",
    admin_lbl_city: "City *",
    admin_lbl_price: "List Price (EGP) *",
    admin_lbl_buy_now: "Buy Now Price",
    admin_lbl_description: "Description",
    admin_lbl_new_car: "Brand New Car",
    admin_lbl_verified: "Verified Listing",
    admin_lbl_featured: "Featured",
    admin_lbl_mileage: "Mileage (km)",
    admin_lbl_fuel: "Fuel Type",
    admin_lbl_hp: "Horsepower",
    admin_lbl_engine: "Engine",
    admin_lbl_transmission: "Transmission",
    admin_lbl_drivetrain: "Drivetrain",
    admin_lbl_seats: "Seats",
    admin_lbl_overall: "Overall Condition",
    admin_lbl_service: "Service History",
    admin_lbl_battery_health: "Battery Health",
    admin_lbl_tires: "Tire Condition",
    admin_lbl_paint: "Paint Condition",
    admin_lbl_accidents: "Accident History",
    admin_lbl_prev_owners: "Previous Owners",
    admin_lbl_license: "License Expiry",
    admin_lbl_main_image: "Main Image URL or Upload",
    admin_lbl_upload_file: "Upload from file",
    admin_lbl_image_url: "Image URL…",
    admin_lbl_video_url: "YouTube / video URL…",
    admin_lbl_doc_url: "Document URL…",
    admin_lbl_starting: "Starting Price",
    admin_lbl_current_bid: "Current Bid",
    admin_lbl_reserve: "Reserve Price",
    admin_lbl_min_raise: "Min. Raise",
    admin_lbl_end_time: "End Date & Time",
    admin_lbl_live: "Live Auction",
    admin_save_changes: "Save Changes",
    admin_go_live: "Go Live",
    admin_go_live_confirm: "Going Live…",
    admin_unlist: "Unlist",
    admin_feature: "Feature",
    admin_unfeature: "Unfeature",
    admin_action_edit: "Edit",
    admin_action_delete: "Delete",
    admin_lbl_accident: "Accident:",
    admin_lbl_reserve_lbl: "Reserve:",
    admin_year_na: "Year N/A",
    admin_custom_option_ph: "Add custom option…",
    admin_add_option: "Add",
    admin_go_live_title: "Go Live",
    admin_go_live_p: "Set when this auction ends. Bidding starts immediately.",
    admin_status_live: "Live",
    admin_status_listed: "Listed",
    admin_csv_yes: "Yes",
    admin_csv_no: "No",

    val_excellent: "Excellent",
    val_very_good: "Very Good",
    val_good: "Good",
    val_fair: "Fair",
    val_poor: "Poor",
    val_unknown: "Unknown",
    val_clean: "Clean",
    val_salvage: "Salvage",
    val_rebuilt: "Rebuilt",
    val_export_only: "Export Only",
    val_petrol: "Petrol",
    val_diesel: "Diesel",
    val_electric: "Electric",
    val_hybrid: "Hybrid",
    val_plugin_hybrid: "Plug-in Hybrid",
    val_automatic: "Automatic",
    val_manual: "Manual",
    val_cvt: "CVT",
    val_dct: "DCT",
    val_pdk: "PDK",
    val_rwd: "RWD",
    val_fwd: "FWD",
    val_awd: "AWD",
    val_4wd: "4WD",
    val_full: "Full",
    val_partial: "Partial",
    val_dealer_serviced: "Dealer Serviced",
    val_owner_serviced: "Owner Serviced",
    val_none: "None",
    val_new: "New",
    val_like_new: "Like New",
    val_worn: "Worn",
    val_replace: "Replace",
    val_original: "Original",
    val_repainted_partial: "Repainted Partial",
    val_full_repaint: "Full Repaint",
    val_matte_wrap: "Matte Wrap",
    val_pending: "pending",
    val_approved: "approved",
    val_rejected: "rejected",
  },

  ar: {
    // Header
    nav_browse: "تصفح",
    nav_auctions: "المزادات المباشرة",
    nav_admin: "الإدارة",
    nav_list: "أضف سيارتك",
    nav_favorites: "المفضلة",
    nav_admin_panel: "لوحة التحكم",
    nav_sign_out: "تسجيل الخروج",

    // Home Hero
    hero_badge: "{s} مزاد مباشر يعمل الآن",
    hero_h1_1: "هنا تلاقي",
    hero_h1_2: "سيارات مميزة",
    hero_h1_3: "بأفضل الأسعار.",
    hero_p: "تصفح مخزوننا الموثق، شارك في المزادات المباشرة، واربح السيارة التي تريدها — مع حماية كاملة.",
    hero_btn_auction: "ادخل المزاد المباشر",
    hero_btn_browse: "تصفح السيارات",
    hero_stat_listed: "سيارة مدرجة",
    hero_stat_live: "مباشر الآن",
    hero_stat_verified: "موثق",
    hero_viewers: "مشاهد",
    hero_bid_now: "زايد الآن",

    // Search
    search_placeholder: "مثلاً: تويوتا، بي إم، القاهرة…",
    search_btn: "بحث",

    // Home sections
    live_now: "مباشر الآن",
    bidding_in_progress: "المزايدة جارية",
    view_all: "عرض الكل",
    all_cars: "كل السيارات",
    curated: "مختارة",
    featured_inventory: "سيارات مميزة",
    new_cars_section: "سيارات جديدة",
    used_cars_section: "سيارات مستعملة",
    new_cars_label: "صفر كيلو",
    used_cars_label: "مستعملة",

    // Features
    feat1_title: "سيارات موثقة",
    feat1_desc: "كل سيارة مفحوصة وموثقة. كل إعلان يأتي بتقرير حالة كامل.",
    feat2_title: "مزايدة فورية",
    feat2_desc: "تحديثات فورية. شاهد كل عرض في اللحظة التي يحدث فيها.",
    feat3_title: "تحليل أسعار بالذكاء الاصطناعي",
    feat3_desc: "اعرف السعر العادل قبل ما تزايد. تسعير تنبؤي لكل سيارة.",

    // CTA (kept for potential future use)
    cta_h: "ابحث عن",
    cta_h2: "سيارتك المميزة.",
    cta_p: "تصفح {n}+ إعلان موثق، شارك في المزادات، واقود بثقة.",
    cta_btn1: "تصفح السيارات",
    cta_btn2: "تواصل معنا",

    // Browse
    browse_title: "تصفح السيارات",
    browse_mobile_ph: "الماركة، الموديل، المدينة…",
    browse_filters: "تصفية",
    browse_active: "{n} نشط",
    browse_brand: "الماركة",
    browse_all_brands: "كل الماركات",
    browse_city: "المدينة",
    browse_all_cities: "كل المدن",
    browse_max_price: "أقصى سعر",
    browse_live_only: "المزادات المباشرة فقط",
    browse_reset: "إعادة ضبط",
    browse_results: "{n} سيارة",
    browse_no_results: "لا توجد سيارات تطابق الفلاتر.",
    browse_reset_filters: "إعادة الفلاتر",
    browse_car_type: "نوع السيارة",
    browse_type_all: "الكل",

    // Auctions
    auctions_title: "المزادات المباشرة",
    auctions_p: "ادفع رسوم الدخول، زايد في الوقت الفعلي، واربح سيارات مميزة مع حماية كاملة للمشتري.",
    auctions_none_title: "لا توجد مزادات مباشرة الآن",
    auctions_none_p: "عد لاحقاً أو تصفح كل السيارات.",
    auctions_browse: "تصفح السيارات",
    auctions_ends_in: "ينتهي خلال",
    auctions_bids: "عرض",
    auctions_bid_now: "زايد الآن",
    auctions_upcoming: "قادم",
    auctions_upcoming_title: "مزادات قادمة",
    auctions_upcoming_p: "هذه السيارات ستُعرض للمزاد قريباً.",
    auctions_notify: "أشعرني",

    // Car detail
    car_live_badge: "مزاد مباشر",
    car_verified: "موثق",
    car_watching: "يشاهد الآن",
    car_specs: "المواصفات",
    car_condition: "تقرير الحالة",
    car_options_title: "مواصفات إضافية",
    car_current_bid: "العرض الحالي",
    car_ends_in: "ينتهي خلال",
    car_your_bid: "عرضك",
    car_place_bid: "قدّم عرضاً",
    car_placing: "جارٍ التقديم…",
    car_entry_fee: "رسوم الدخول {n} · تُسترد إن لم تفز",
    car_bid_history: "سجل العروض",
    car_buy_now: "اشتري الآن",
    car_buy_now_price: "سعر الشراء الفوري",
    car_reserve_not_met: "لم يبلغ الحد الأدنى",
    car_contact: "تواصل مع الوكيل",
    car_back: "تصفح",
    car_share: "مشاركة",
    car_related: "قد يعجبك أيضاً",
    car_overall: "التقييم العام",
    car_accidents: "حوادث سابقة",
    car_no_accidents: "لا يوجد",
    car_accident_yes: "نعم — مُفصح عنه",
    car_service: "سجل الصيانة",

    // CarCard
    card_current_bid: "العرض الحالي",
    card_buy_now: "اشتري الآن",
    card_bids: "عروض",
    card_verified: "موثق",
    card_fav_add: "أُضيف للمفضلة ♥",
    card_fav_remove: "حُذف من المفضلة",

    // Footer
    footer_tagline: "وجهتك المميزة لمزادات السيارات المستعملة. مخزون موثق، مزايدة مباشرة، مدفوعات آمنة.",
    footer_marketplace: "السوق",
    footer_company: "الشركة",
    footer_support: "الدعم",
    footer_browse: "تصفح",
    footer_auctions: "المزادات المباشرة",
    footer_featured: "المميزة",
    footer_list: "أضف سيارتك",
    footer_about: "من نحن",
    footer_careers: "وظائف",
    footer_press: "الصحافة",
    footer_contact: "تواصل معنا",
    footer_help: "مركز المساعدة",
    footer_protection: "حماية المشتري",
    footer_verification: "التوثيق",
    footer_terms: "الشروط",
    footer_copy: "© 2026 APEXAuto. جميع الحقوق محفوظة.",
    footer_crafted: "صُنع للمحبين.",

    // List your car
    list_badge: "برنامج الإدراج الموثق",
    list_title: "أضف سيارتك. بعها أسرع.",
    list_p: "انضم لأسرع منصة مزادات سيارات مميزة في مصر وتواصل مع مشترين جادين فوراً.",
    list_name: "الاسم الكامل *",
    list_email: "البريد الإلكتروني *",
    list_phone: "رقم الهاتف",
    list_brand: "ماركة السيارة *",
    list_model: "الموديل *",
    list_year: "السنة",
    list_price: "السعر المتوقع (EGP)",
    list_submit: "إرسال طلب الإدراج",
    list_success_title: "تم استلام طلبك!",
    list_success_p: "سيتواصل معك فريقنا خلال 24 ساعة لإتمام إدراج سيارتك.",
    list_success_back: "العودة للرئيسية",

    // Favorites
    fav_title: "المفضلة",
    fav_empty: "لا يوجد مفضلات بعد",
    fav_empty_p: "اضغط على القلب لحفظ سيارة هنا.",
    fav_browse: "تصفح السيارات",

    // Condition labels
    cond_engine: "حالة الموتور",
    cond_transmission: "حالة الفتيس",
    cond_suspension: "حالة العفشة",
    cond_battery: "حالة البطارية",
    cond_tires: "حالة الإطارات",
    cond_chassis: "حالة الشاسيه",
    cond_interior: "حالة الصالون",
    cond_paint: "هل رشة؟",
    cond_prev_owners: "عدد الملاك",
    cond_license: "الرخصة سارية حتى",

    // Options labels
    opt_sunroof: "فتحة سقف",
    opt_rear_camera: "كاميرا خلفية",
    opt_parking_sensors: "حساسات ركن",
    opt_infotainment: "شاشة داخلية",
    opt_navigation: "نظام ملاحة",
    opt_leather_seats: "فرش جلد",
    opt_heated_seats: "تسخين مقاعد",
    opt_ventilated_seats: "تبريد مقاعد",
    opt_cruise_control: "مثبت سرعة",
    opt_keyless_entry: "دخول بدون مفتاح",
    opt_push_start: "زر تشغيل",
    opt_auto_ac: "تكييف أوتوماتيك",
    opt_abs: "فرامل ABS",
    opt_esp: "نظام ESP",
    opt_airbags: "وسائد هوائية",
    opt_options_title: "مواصفات إضافية",

    // Admin
    admin_super: "مشرف أعلى",
    admin_ctrl: "لوحة",
    admin_ctrl2: "التحكم",
    admin_export_csv: "تصدير CSV",
    admin_add_car: "إضافة سيارة",
    admin_stat_sold_val: "قيمة السيارات المباعة",
    admin_stat_live: "مزادات مباشرة",
    admin_stat_cars: "إجمالي السيارات",
    admin_stat_users: "المستخدمون المسجلون",
    admin_chart_title: "إيرادات المزادات",
    admin_chart_sub: "آخر 12 أسبوع",
    admin_live_mon: "المراقبة المباشرة",
    admin_no_live: "لا توجد مزادات مباشرة الآن.",
    admin_inventory: "مخزون السيارات",
    admin_submissions: "طلبات الإدراج",
    admin_submissions_sub: "سيارات تم تقديمها عبر \"أضف سيارتك\"",
    admin_hero_spot: "البطل المميز",
    admin_hero_sub: "السيارة المعروضة في بطل الصفحة الرئيسية. يتم اختيارها تلقائياً، أو يمكن تثبيت سيارة يدوياً.",
    admin_hero_pin: "تثبيت سيارة محددة في بطل الصفحة",
    admin_hero_auto: "— تلقائي (أقرب مزاد أو أفضل سيارة) —",
    admin_hero_save: "حفظ",
    admin_hero_clear: "إلغاء التثبيت",
    admin_pinned: "مثبّت",
    admin_auto_sel: "مختار تلقائياً",
    admin_entry_req: "طلبات الدخول للمزاد",
    admin_entry_sub: "طلبات إثبات الدفع اليدوي للمزادات المباشرة",
    admin_deposit_cfg: "إعدادات التأمين",
    admin_deposit_amt: "مبلغ التأمين (جنيه)",
    admin_pay_info: "معلومات الدفع (تظهر للمستخدم)",
    admin_save_settings: "حفظ الإعدادات",
    admin_approve_entry: "قبول الدخول",
    admin_approve: "قبول",
    admin_reject: "رفض",
    admin_reset_pending: "إعادة للانتظار",
    admin_view_proof: "عرض إيصال الدفع",
    admin_hide_proof: "إخفاء الإيصال",
    admin_reject_reason: "سبب الرفض (اختياري)",
    admin_refund_ip: "رقم Instapay للاسترداد:",
    admin_deposit_lbl: "التأمين:",
    admin_car_lbl: "السيارة:",
    admin_no_entries: "لا توجد طلبات دخول بعد.",
    admin_sold_arch: "أرشيف السيارات المباعة",
    admin_sold_sub: "مزادات مكتملة ومبيعات مباشرة",
    admin_reg_users: "المستخدمون المسجلون",
    admin_reg_users_sub: "مستخدمون سجّلوا عبر صفحة تسجيل الدخول",
    admin_messages: "رسائل المشترين",
    admin_messages_sub: "محادثات من صفحات تفاصيل السيارات",
    admin_no_msgs: "لا توجد رسائل بعد.",
    admin_reply_ph: "رد كوكيل…",
    admin_reply: "رد",
    admin_sending: "جارٍ الإرسال…",
    admin_you_admin: "أنت (المشرف)",
    admin_breakdown: "توزيع المخزون",
    admin_by_brand: "السيارات حسب الماركة",
    admin_total: "إجمالي",
    admin_pending: "بانتظار المراجعة",
    admin_conversations: "محادثات",
    admin_no_subs: "لا توجد طلبات بعد.",
    admin_no_sold: "لا توجد سيارات مباعة بعد.",
    admin_no_users: "لا يوجد مستخدمون مسجلون بعد.",
    admin_click_full: "اضغط على الصورة للعرض الكامل",
    admin_tab_overview: "نظرة عامة",
    admin_tab_cars: "السيارات",
    admin_tab_requests: "الطلبات",
    admin_tab_people: "المستخدمين",

    nav_home: "الرئيسية",
    nav_calendar: "التقويم",
    nav_sell: "بيع",
    nav_saved: "المفضلة",
    badge_live: "مباشر",
    badge_sold: "مباع",
    badge_best: "الأفضل",
    badge_upcoming: "مزاد قادم",
    badge_verified_buyer: "مشتري موثق",
    common_yes: "نعم",
    common_no: "لا",
    common_close: "إغلاق",
    common_saving: "جارٍ الحفظ…",
    common_submitting: "جارٍ الإرسال…",
    common_user: "مستخدم",
    common_more: "المزيد",
    common_none: "لا يوجد",
    common_ended: "انتهى",
    common_unknown: "غير معروف",
    common_na: "—",

    header_search_ph: "ابحث عن ماركة، موديل، مدينة…",
    header_search_see_all: 'عرض كل النتائج لـ "{q}"',
    header_search_none: 'لا توجد سيارات لـ "{q}"',
    header_search_type: "اكتب للبحث عن سيارات…",
    header_notif_title: "الإشعارات",
    header_notif_view_all: "عرض الكل",
    header_notif_empty: "لا توجد إشعارات بعد",

    footer_toast_about: "صفحة من نحن قريباً",
    footer_toast_careers: "صفحة الوظائف قريباً",
    footer_toast_press: "حزمة الصحافة قريباً",
    footer_toast_contact: "تواصل معنا: hello@apexauto.com",
    footer_toast_help: "مركز المساعدة قريباً",
    footer_toast_protection: "كل المشتريات تشمل حماية كاملة للمشتري",
    footer_toast_verification: "كل الوكلاء موثقون",
    footer_toast_terms: "شروط الخدمة متاحة عند الطلب",

    toast_img_upload_ok: "تم رفع الصورة بنجاح",
    toast_img_upload_fail: "فشل رفع الصورة",
    toast_hero_updated: "تم تحديث السيارة المميزة",
    toast_hero_auto: "تم ضبط السيارة المميزة على تلقائي",
    toast_hero_fail: "فشل تحديث السيارة المميزة",
    toast_entry_approved: "تم قبول الدخول — يمكن للمستخدم المزايدة الآن",
    toast_entry_status: "طلب الدخول: {status}",
    toast_entry_fail: "فشل تحديث حالة الدخول",
    toast_deposit_saved: "تم حفظ إعدادات التأمين",
    toast_settings_fail: "فشل حفظ الإعدادات",
    toast_request_status: "الطلب: {status}",
    toast_request_fail: "فشل تحديث الحالة",
    toast_reply_sent: "تم إرسال الرد",
    toast_reply_fail: "فشل إرسال الرد",
    toast_csv_exported: "تم تصدير المخزون CSV",
    toast_fill_required: "أكمل الحقول المطلوبة: العنوان، الماركة، الموديل، الوكالة، المدينة",
    toast_car_updated: "تم تحديث {title}",
    toast_car_added: "تمت إضافة {title} للمخزون",
    toast_save_fail: "فشل الحفظ",
    toast_car_deleted: "تم حذف {title}",
    toast_delete_fail: "فشل الحذف",
    toast_car_unlisted: "تم إلغاء إدراج {title}",
    toast_update_fail: "فشل التحديث",
    toast_valid_end: "حدد تاريخ ووقت انتهاء صالح",
    toast_end_future: "يجب أن يكون وقت الانتهاء في المستقبل",
    toast_now_live: "{title} أصبحت مباشرة الآن!",
    toast_go_live_fail: "فشل تفعيل المزاد",
    toast_featured: "تم تمييز {title}",
    toast_unfeatured: "تم إلغاء تمييز {title}",
    toast_auction_end_set: "تم ضبط انتهاء المزاد بعد {duration}",
    toast_duration_minutes: "{n} دقيقة",
    toast_duration_hours: "{n} ساعة",
    toast_week_revenue: "الأسبوع {n}: {amount} جنيه",
    toast_fill_fields: "يرجى ملء جميع الحقول المطلوبة",
    toast_submit_fail: "فشل إرسال الطلب. حاول مرة أخرى.",
    toast_upload_proof: "يرجى رفع لقطة شاشة الدفع",
    toast_instapay_required: "يرجى إدخال رقم Instapay للاسترداد",
    toast_entry_submitted: "تم إرسال الطلب — سيراجعه المشرف قريباً.",
    toast_bid_placed: "تم تقديم العرض: {amount} ✓",
    toast_bid_fail: "فشل تقديم العرض",
    toast_sign_in_bid: "سجّل الدخول لتقديم عرض",
    toast_min_bid: "الحد الأدنى للعرض {amount}",
    toast_entry_pending: "طلب الدخول قيد مراجعة المشرف.",
    toast_link_copied: "تم نسخ الرابط!",
    toast_compare_removed: "تمت الإزالة من المقارنة",
    toast_compare_added: "تمت الإضافة للمقارنة",
    toast_compare_max: "يمكن مقارنة 3 سيارات كحد أقصى",
    toast_proxy_min: "يجب أن يكون الحد الأقصى أكبر من العرض الحالي {amount}",
    toast_proxy_set: "تم ضبط العرض التلقائي على {amount}. سنزايد تلقائياً حتى هذا المبلغ.",
    toast_proxy_fail: "فشل ضبط العرض التلقائي",
    toast_price_alert_removed: "تم إلغاء تنبيه السعر",
    toast_price_alert_set: "تم ضبط تنبيه السعر على {amount}",
    toast_popup_blocked: "يرجى السماح بالنوافذ المنبثقة للطباعة",
    toast_msg_fail: "فشل إرسال الرسالة",
    toast_reservation_ok: "تم تأكيد الحجز! سنتواصل معك خلال ساعتين.",

    notif_entry_submitted_title: "تم إرسال طلب الدخول للمزاد",
    notif_entry_submitted_body: "تم إرسال إثبات التأمين لـ {car}. سنُبلغك عند مراجعة المشرف.",
    notif_entry_approved_title: "تم قبول الدخول للمزاد",
    notif_entry_approved_body: "يمكنك الآن المزايدة على {car}. بالتوفيق!",
    notif_entry_rejected_title: "لم يُقبل الدخول للمزاد",
    notif_entry_rejected_body: "لم يُقبل طلب الدخول لـ {car}. ارفع إثباتاً جديداً للمحاولة مرة أخرى.",

    sell_hero_badge: "أضف سيارتك",
    sell_hero_title: "بيع عبر APEXAuto",
    sell_hero_p: "أرسل تفاصيل سيارتك وسيراجع فريقنا طلب الإدراج. سنتواصل معك خلال 24 ساعة.",
    sell_why_price: "أفضل سعر",
    sell_why_price_d: "تسعير مزاد تنافسي",
    sell_why_verified: "موثق",
    sell_why_verified_d: "فحص كامل",
    sell_why_fast: "سريع",
    sell_why_fast_d: "إدراج خلال 48 ساعة",
    sell_success_title: "تم إرسال الطلب!",
    sell_success_p: "سيراجع فريقنا إدراجك ويتواصل معك على {email} خلال 24 ساعة.",
    sell_browse: "تصفح السيارات",
    sell_another: "إرسال طلب آخر",
    sell_info_title: "بياناتك",
    sell_info_sub: "سنستخدمها للتواصل معك بخصوص الإدراج",
    sell_car_title: "تفاصيل السيارة",
    sell_car_sub: "أخبرنا عن السيارة التي تريد بيعها",
    sell_notes: "ملاحظات إضافية",
    sell_notes_ph: "الحالة، الكيلومترات، التعديلات، سجل الصيانة، سبب البيع…",
    sell_asking_price: "السعر المطلوب (جنيه)",
    sell_agree: "بالإرسال، توافق على عملية المراجعة. سيتواصل فريقنا خلال 24 ساعة.",
    sell_email: "البريد الإلكتروني",

    entry_title: "طلب الدخول للمزاد",
    entry_deposit_required: "مطلوب تأمين للانضمام لهذا المزاد",
    entry_refund_note: "إن لم تفز، {pct} من تأمينك (EGP {amount}) يُسترد على Instapay.",
    entry_refund_pct: "80% من تأمينك",
    entry_fee_note: "الـ 20% المتبقية (EGP {amount}) تغطي رسوم إدارية ولا تُسترد.",
    entry_transfer_to: "حوّل إلى",
    entry_pay_not_configured: "بيانات الدفع غير مُعدّة. تواصل مع الإدارة.",
    entry_instapay: "رقم Instapay الخاص بك",
    entry_instapay_hint: "سنرسل الاسترداد لهذا الرقم إن لم تفز.",
    entry_instapay_ph: "مثال: 01012345678",
    entry_upload_proof: "رفع إثبات الدفع",
    entry_upload_hint: "لقطة شاشة من Instapay أو تأكيد التحويل البنكي.",
    entry_upload_click: "اضغط لرفع لقطة الشاشة",
    entry_submit: "إرسال الطلب",
    entry_approved: "يمكنك المزايدة في هذا المزاد",
    entry_pending: "طلب الدخول قيد المراجعة",
    entry_rejected: "تم رفض الدخول. ارفع إثباتاً جديداً.",
    entry_request_btn: "طلب الدخول",

    car_not_found: "السيارة غير موجودة",
    car_back_browse: "العودة للتصفح",
    car_has_accidents: "يوجد حوادث",
    car_no_accidents_label: "لا حوادث",
    car_overall_condition: "الحالة العامة",
    car_hp_unit: "{n} حصان",
    car_km_unit: "{n} كم",

    compare_title: "مقارنة السيارات",
    compare_empty_p: "أضف سيارات من التصفح للمقارنة جنباً إلى جنب.",
    compare_count: "مقارنة {n} سيارة",
    compare_clear: "مسح الكل",
    compare_none_title: "لا سيارات للمقارنة",
    compare_none_p: "اذهب للتصفح واضغط أيقونة المقارنة على أي سيارة.",
    compare_view_listing: "عرض الإعلان",
    compare_spec_price: "السعر",
    compare_spec_year: "السنة",
    compare_spec_mileage: "الكيلومترات",
    compare_spec_engine: "المحرك",
    compare_spec_hp: "القوة",
    compare_spec_fuel: "الوقود",
    compare_spec_transmission: "ناقل الحركة",
    compare_spec_color: "اللون",
    compare_spec_seats: "المقاعد",
    compare_spec_condition: "الحالة",
    compare_spec_accidents: "حوادث سابقة",
    compare_spec_city: "المدينة",
    compare_spec_dealer: "الوكالة",
    compare_spec_options: "المواصفات",

    calendar_badge: "الجدول",
    calendar_title: "تقويم المزادات",
    calendar_p: "تابع مواعيد انتهاء المزادات المباشرة والقادمة.",
    calendar_live_count: "{n} مباشر الآن",
    calendar_no_end: "بدون تاريخ انتهاء",
    calendar_upcoming: "قادم ({n})",
    calendar_none: "لا مزادات قادمة مجدولة.",
    calendar_view_live: "عرض المزادات المباشرة",

    sold_badge: "أرشيف المزادات",
    sold_title: "السيارات المباعة",
    sold_p: "تصفح المزادات المكتملة وأسعار البيع النهائية.",
    sold_stat_total: "إجمالي المباع",
    sold_stat_value: "إجمالي القيمة",
    sold_stat_avg: "متوسط سعر البيع",
    sold_stat_record: "أعلى سعر",
    sold_empty_title: "لا مبيعات بعد",
    sold_empty_p: "ستظهر المزادات المكتملة هنا بعد إغلاق المزاد.",
    sold_final_price: "السعر النهائي",
    sold_starting: "الافتتاح:",
    sold_bids: "{n} عرض",

    account_tab_bids: "عروضي",
    account_tab_notif: "الإشعارات",
    account_tab_recent: "شوهدت مؤخراً",
    account_tab_searches: "عمليات البحث المحفوظة",
    account_tab_profile: "الملف الشخصي",
    account_stat_bids: "إجمالي العروض",
    account_stat_cars: "سيارات زايدت عليها",
    account_stat_active: "نشط",
    account_stat_won: "فزت",
    account_stat_favorites: "المفضلة",
    account_clear_notif: "مسح الكل",
    account_mark_read: "تعليم الكل كمقروء",
    account_no_bids: "لا عروض بعد",
    account_no_bids_p: "انضم لمزاد مباشر وقدّم أول عرض.",
    account_view_auctions: "عرض المزادات المباشرة",
    account_no_notif: "لا إشعارات",
    account_no_recent: "لا سيارات شوهدت مؤخراً",
    account_no_searches: "لا عمليات بحث محفوظة",
    account_save_search: "حفظ البحث",
    account_search_ph: "عبارة البحث…",
    account_profile_title: "إعدادات الملف",
    account_name: "الاسم الكامل",
    account_email: "البريد الإلكتروني",
    account_phone: "الهاتف",
    account_save: "حفظ الملف",
    account_sign_out: "تسجيل الخروج",
    account_bid_on: "عرض على",
    account_status_won: "فزت",
    account_status_outbid: "تجاوزك",
    account_status_active: "نشط",
    account_status_ended: "انتهى",

    auth_tagline: "مزادات سيارات مميزة",

    admin_form_edit: "تعديل السيارة",
    admin_form_add: "إضافة سيارة جديدة",
    admin_form_editing: "تعديل: {title}",
    admin_form_subtitle: "أكمل كل الأقسام للحصول على أفضل النتائج",
    admin_form_tab_basic: "معلومات أساسية",
    admin_form_tab_mechanical: "ميكانيكا",
    admin_form_tab_condition: "الحالة",
    admin_form_tab_options: "مواصفات",
    admin_form_tab_media: "وسائط",
    admin_form_tab_auction: "المزاد",
    admin_sec_identity: "الهوية",
    admin_sec_location: "الموقع والوكالة",
    admin_sec_pricing: "التسعير",
    admin_sec_description: "الوصف",
    admin_sec_flags: "خيارات",
    admin_sec_engine: "المحرك والقوة",
    admin_sec_drivetrain: "ناقل الحركة والمواصفات",
    admin_sec_primary_img: "الصورة الرئيسية",
    admin_sec_gallery: "معرض الصور",
    admin_sec_videos: "فيديوهات",
    admin_sec_auction_pricing: "تسعير المزاد",
    admin_sec_auction_end: "وقت انتهاء المزاد",
    admin_sec_auction_status: "حالة المزاد",
    admin_lbl_title: "العنوان *",
    admin_lbl_brand: "الماركة *",
    admin_lbl_model: "الموديل *",
    admin_lbl_year: "السنة",
    admin_lbl_trim: "الفئة",
    admin_lbl_vin: "رقم الشاسيه",
    admin_lbl_plate: "حالة اللوحة",
    admin_lbl_color: "اللون",
    admin_lbl_dealership: "الوكالة *",
    admin_lbl_city: "المدينة *",
    admin_lbl_price: "سعر الإدراج (جنيه) *",
    admin_lbl_buy_now: "سعر الشراء الفوري",
    admin_lbl_description: "الوصف",
    admin_lbl_new_car: "سيارة جديدة",
    admin_lbl_verified: "إعلان موثق",
    admin_lbl_featured: "مميزة",
    admin_lbl_mileage: "الكيلومترات (كم)",
    admin_lbl_fuel: "نوع الوقود",
    admin_lbl_hp: "القوة (حصان)",
    admin_lbl_engine: "المحرك",
    admin_lbl_transmission: "ناقل الحركة",
    admin_lbl_drivetrain: "نظام الدفع",
    admin_lbl_seats: "المقاعد",
    admin_lbl_overall: "الحالة العامة",
    admin_lbl_service: "سجل الصيانة",
    admin_lbl_battery_health: "حالة البطارية",
    admin_lbl_tires: "حالة الإطارات",
    admin_lbl_paint: "حالة الطلاء",
    admin_lbl_accidents: "حوادث سابقة",
    admin_lbl_prev_owners: "عدد الملاك",
    admin_lbl_license: "انتهاء الرخصة",
    admin_lbl_main_image: "رابط الصورة أو رفع ملف",
    admin_lbl_upload_file: "رفع من الجهاز",
    admin_lbl_image_url: "رابط الصورة…",
    admin_lbl_video_url: "رابط يوتيوب / فيديو…",
    admin_lbl_doc_url: "رابط مستند…",
    admin_lbl_starting: "سعر الافتتاح",
    admin_lbl_current_bid: "العرض الحالي",
    admin_lbl_reserve: "الحد الأدنى للبيع",
    admin_lbl_min_raise: "الحد الأدنى للزيادة",
    admin_lbl_end_time: "تاريخ ووقت الانتهاء",
    admin_lbl_live: "مزاد مباشر",
    admin_save_changes: "حفظ التغييرات",
    admin_go_live: "تفعيل المزاد",
    admin_go_live_confirm: "جارٍ التفعيل…",
    admin_unlist: "إلغاء الإدراج",
    admin_feature: "تمييز",
    admin_unfeature: "إلغاء التمييز",
    admin_action_edit: "تعديل",
    admin_action_delete: "حذف",
    admin_lbl_accident: "حادث:",
    admin_lbl_reserve_lbl: "الحد الأدنى:",
    admin_year_na: "السنة غير متاحة",
    admin_custom_option_ph: "أضف مواصفة مخصصة…",
    admin_add_option: "إضافة",
    admin_go_live_title: "تفعيل المزاد",
    admin_go_live_p: "حدد وقت انتهاء المزاد. تبدأ المزايدة فوراً.",
    admin_status_live: "مباشر",
    admin_status_listed: "مدرج",
    admin_csv_yes: "نعم",
    admin_csv_no: "لا",

    val_excellent: "ممتاز",
    val_very_good: "جيد جداً",
    val_good: "جيد",
    val_fair: "مقبول",
    val_poor: "ضعيف",
    val_unknown: "غير معروف",
    val_clean: "نظيفة",
    val_salvage: "تالفة",
    val_rebuilt: "معاد بناؤها",
    val_export_only: "تصدير فقط",
    val_petrol: "بنزين",
    val_diesel: "ديزل",
    val_electric: "كهرباء",
    val_hybrid: "هجين",
    val_plugin_hybrid: "هجين قابل للشحن",
    val_automatic: "أوتوماتيك",
    val_manual: "مانيوال",
    val_cvt: "CVT",
    val_dct: "DCT",
    val_pdk: "PDK",
    val_rwd: "خلفي",
    val_fwd: "أمامي",
    val_awd: "رباعي",
    val_4wd: "4×4",
    val_full: "كامل",
    val_partial: "جزئي",
    val_dealer_serviced: "صيانة وكالة",
    val_owner_serviced: "صيانة مالك",
    val_none: "لا يوجد",
    val_new: "جديد",
    val_like_new: "كالجديد",
    val_worn: "متهالك",
    val_replace: "يحتاج استبدال",
    val_original: "أصلي",
    val_repainted_partial: "رش جزئي",
    val_full_repaint: "رش كامل",
    val_matte_wrap: "لف مطفي",
    val_pending: "قيد المراجعة",
    val_approved: "مقبول",
    val_rejected: "مرفوض",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

const VALUE_KEY_MAP: Record<string, TranslationKey> = {
  Excellent: "val_excellent",
  "Very Good": "val_very_good",
  Good: "val_good",
  Fair: "val_fair",
  Poor: "val_poor",
  Unknown: "val_unknown",
  Clean: "val_clean",
  Salvage: "val_salvage",
  Rebuilt: "val_rebuilt",
  "Export Only": "val_export_only",
  Petrol: "val_petrol",
  Diesel: "val_diesel",
  Electric: "val_electric",
  Hybrid: "val_hybrid",
  "Plug-in Hybrid": "val_plugin_hybrid",
  Automatic: "val_automatic",
  Manual: "val_manual",
  CVT: "val_cvt",
  DCT: "val_dct",
  PDK: "val_pdk",
  RWD: "val_rwd",
  FWD: "val_fwd",
  AWD: "val_awd",
  "4WD": "val_4wd",
  Full: "val_full",
  Partial: "val_partial",
  "Dealer Serviced": "val_dealer_serviced",
  "Owner Serviced": "val_owner_serviced",
  None: "val_none",
  New: "val_new",
  "Like New": "val_like_new",
  Worn: "val_worn",
  Replace: "val_replace",
  Original: "val_original",
  "Repainted Partial": "val_repainted_partial",
  "Full Repaint": "val_full_repaint",
  "Matte Wrap": "val_matte_wrap",
  Yes: "common_yes",
  No: "common_no",
  Live: "admin_status_live",
  Listed: "admin_status_listed",
  pending: "val_pending",
  approved: "val_approved",
  rejected: "val_rejected",
};

export function tv(t: (key: TranslationKey, vars?: Record<string, string | number>) => string, value: string | null | undefined): string {
  if (value == null || value === "") return "—";
  const key = VALUE_KEY_MAP[value];
  return key ? t(key) : value;
}

const NOTIF_TYPE_KEYS: Partial<Record<string, { title: TranslationKey; body: TranslationKey }>> = {
  entry_submitted: { title: "notif_entry_submitted_title", body: "notif_entry_submitted_body" },
  entry_approved: { title: "notif_entry_approved_title", body: "notif_entry_approved_body" },
  entry_rejected: { title: "notif_entry_rejected_title", body: "notif_entry_rejected_body" },
};

export function getNotificationText(
  n: { type: string; title: string; body: string; vars?: Record<string, string | number> },
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string,
): { title: string; body: string } {
  const keys = NOTIF_TYPE_KEYS[n.type];
  if (keys) {
    const vars = n.vars ?? extractCarVar(n.body);
    return { title: t(keys.title), body: t(keys.body, vars) };
  }
  return { title: n.title, body: n.body };
}

function extractCarVar(body: string): Record<string, string> {
  const m = body.match(/for (.+?) has been|on (.+?)\.|for (.+?) was not/);
  const car = m?.[1] ?? m?.[2] ?? m?.[3];
  return car ? { car } : {};
}

type LangContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
  isAr: boolean;
};

const LangContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = localStorage.getItem("apex_lang") as Lang | null;
    if (stored && stored !== lang) {
      setLangState(stored);
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("apex_lang", l);
  };

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute("dir", lang === "ar" ? "rtl" : "ltr");
    html.setAttribute("lang", lang);
  }, [lang]);

  const t = (key: TranslationKey, vars?: Record<string, string | number>): string => {
    let str = (translations[lang] as Record<string, string>)[key] ?? (translations.en as Record<string, string>)[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, String(v));
      });
    }
    return str;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, isAr: lang === "ar" }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
