// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/payment-verification/PaymentVerification.tsx": () => import("../components/mockups/payment-verification/PaymentVerification.tsx")
};
