/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsX7k9m2RouteImport } from './routes/ops-x7k9m2'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as CarsCarIdRouteImport } from './routes/cars.$carId'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsX7k9m2Route = OpsX7k9m2RouteImport.update({
  id: '/ops-x7k9m2',
  path: '/ops-x7k9m2',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRoute
  '/browse': typeof BrowseRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/ops-x7k9m2': typeof OpsX7k9m2Route
  '/sell': typeof SellRoute
  '/sold': typeof SoldRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRoute
  '/browse': typeof BrowseRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/ops-x7k9m2': typeof OpsX7k9m2Route
  '/sell': typeof SellRoute
  '/sold': typeof SoldRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRoute
  '/browse': typeof BrowseRoute
  '/calendar': typeof CalendarRoute
  '/compare': typeof CompareRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/ops-x7k9m2': typeof OpsX7k9m2Route
  '/sell': typeof SellRoute
  '/sold': typeof SoldRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auctions'
    | '/browse'
    | '/calendar'
    | '/compare'
    | '/create-organization'
    | '/favorites'
    | '/login'
    | '/ops-x7k9m2'
    | '/sell'
    | '/sold'
    | '/cars/$carId'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auctions'
    | '/browse'
    | '/calendar'
    | '/compare'
    | '/create-organization'
    | '/favorites'
    | '/login'
    | '/ops-x7k9m2'
    | '/sell'
    | '/sold'
    | '/cars/$carId'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auctions'
    | '/browse'
    | '/calendar'
    | '/compare'
    | '/create-organization'
    | '/favorites'
    | '/login'
    | '/ops-x7k9m2'
    | '/sell'
    | '/sold'
    | '/cars/$carId'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuctionsRoute: typeof AuctionsRoute
  BrowseRoute: typeof BrowseRoute
  CalendarRoute: typeof CalendarRoute
  CompareRoute: typeof CompareRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  OpsX7k9m2Route: typeof OpsX7k9m2Route
  SellRoute: typeof SellRoute
  SoldRoute: typeof SoldRoute
  CarsCarIdRoute: typeof CarsCarIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-x7k9m2': {
      id: '/ops-x7k9m2'
      path: '/ops-x7k9m2'
      fullPath: '/ops-x7k9m2'
      preLoaderRoute: typeof OpsX7k9m2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuctionsRoute: AuctionsRoute,
  BrowseRoute: BrowseRoute,
  CalendarRoute: CalendarRoute,
  CompareRoute: CompareRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  OpsX7k9m2Route: OpsX7k9m2Route,
  SellRoute: SellRoute,
  SoldRoute: SoldRoute,
  CarsCarIdRoute: CarsCarIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
